baseURL = "https://localhost:1313"
title = "Aloha Theme Example Site"
theme = "aloha"
author = "noname"
canonifyurls = true
languagecode = "en"
paginate = 8
enableGitInfo = true
pygmentsCodefences = true
pygmentsUseClasses = false
#https://help.farbox.com/pygments.html
pygmentsStyle = "algol_nu"
pygmentsCodefencesGuessSyntax = true

[params]
    sitename = "Aloha Theme Example Site"
    description = "Aloha!"
    disableWebFonts = false
    showSummary = true

[[menu.main]]
    name = "Fork Me"
    url  = "https://github.com/number317/aloha.git"
    weight = 1
[[menu.main]]
    name = "Categories"
    url  = "/categories"
    weight = 2
[[menu.main]]
    name = "Tags"
    url  = "/tags"
    weight = 3
    
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
